// generated by "sampctl package generate"

#define MAP_PATH "./Maps/" //root directory of the git repo for test map
#define MAP_FILE_EXTENSION ".txt"
#include "samp-map-parser.inc"

main() 
{
	// write tests for libraries here and run "sampctl package run"
	print("Parsing all maps");
	ProcessMaps();

	print("Exporting map ID 0");
	ExportMap(0);

	print("Unloading map ID 0");
	UnloadMap(0);

	print("Reloading all maps");
	ReprocessMaps();
}

public OnMapLoaded(mapid, const mapname[], List:objects)
{
	printf("[MAP PARSER] %s (ID %i) successfully loaded. [%i objects]", mapname, mapid, list_size(objects));
}
